import { Container, Flex } from '@chakra-ui/react';
import Head from 'next/head';

import { MainNav } from '../src/components/MainNav';
import Cart from '../src/components/cart';
import Details from '../src/components/details';
import { CryptoTable } from '../src/components/crypto/CryptoTable';

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>Crypton - Explore the World of Cryptocurrencies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainNav />
        <Container maxW="container.xl" p={0}>
          <CryptoTable />
          <Flex
            h={{ base: 'auto', md: '100vh' }}
            py={[0, 10, 20]}
            direction={{ base: 'column-reverse', md: 'row' }}
          >
            <Details />
            <Cart />
          </Flex>
        </Container>
      </main>
    </div>
  );
};

export default HomePage;
